# Generated by Django 3.2.16 on 2023-09-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_follow_unique_user_subscribers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_subscribers',
        ),
    ]
